export CONFIG_QTI_TZ_LOG=m
export CONFIG_TZLOG_TIME_CONSOLIDATE=m
export CONFIG_CRYPTO_DEV_QCEDEV=m
export CONFIG_CRYPTO_DEV_QCRYPTO=m
export CONFIG_QCOM_SI_CORE=y
export CONFIG_QCOM_SI_CORE_TEST=m
export CONFIG_QCOM_SMCINVOKE=m
export CONFIG_QSEECOM_COMPAT=m
export CONFIG_QSEECOM_PROXY=m
export CONFIG_QSEECOM=m
export CONFIG_HDCP_QSEECOM=m
export CONFIG_HW_RANDOM_MSM_LEGACY=m
export CONFIG_MSM_TMECOM_QMP=m
